[StateCodelab] Bump to alpha08
googlecodelabs/android-compose-codelabs pull request #62
Opened 2020-12-03 20:02 UTC by objcode

2020-12-03 20:08 UTC, yrezgui requested changes
You need to update AGP (check comment) and Gradle to 6.7.1

2020-12-03 20:08 UTC, yrezgui commented on StateCodelab/build.gradle
> +        classpath "com.android.tools.build:gradle:4.2.0-beta01"
Use `com.android.tools.build:gradle:7.0.0-alpha02` instead

2020-12-07 20:05 UTC, objcode commented on StateCodelab/build.gradle
> +        classpath "com.android.tools.build:gradle:4.2.0-beta01"
Done! PTAL

2020-12-07 23:32 UTC, yrezgui approved these changes

2020-12-07 23:34 UTC, yrezgui commented
I'm merging the PR. I'll update the GitHub action as it needs to set the environment to Java 11

2020-12-07 23:34 UTC, merged